### ISSUE TITLE
add submission element

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#23] opened 2015-02-20 15:57 UTC
@mitchellsundt  wrote:

> If supplied, the one in the form is used. 
> Otherwise, the one in General Settings is used.

(Not supported in Enketo)

**Comment by MartijnR** [comment] 2018-05-08 17:07
In the mean time, we've added a section about encryption that includes `method`, `action` and `base64RsaPublicKey`. It might be good to make the encryption chapter a section under a new Submission chapter (keeping the original link functional)

An inventory of other submission element's features or outstanding spec issues:

* submission type https://github.com/opendatakit/xforms-spec/issues/151
* auto-send and auto-delete https://github.com/opendatakit/xforms-spec/issues/100

**Comment by lognaturel** [comment] 2018-05-08 18:13
> It might be good to make the encryption chapter a section under a new Submission chapter (keeping the original link functional)
 
+1

**Comment by MartijnR** [comment] 2018-05-08 22:37
Continuing on from #100, is the `action` attribute in ODK Collect only used for encrypted data or is it separate from encryption? E.g does`<submission action="https://example.com/submit" method="post">` send a regular unencrypted XML submission to the action URL? 

If ODK Collect doesn't currently do this, I don't feel we need to add this to the spec without a demand for it, but if it does, we can make it describe it like that in the spec. I'm guessing it does.

**Comment by MartijnR** [comment] 2018-05-15 21:53
And a second question that is coming up while rewriting the submission chapter.

Why are `method/action` required to enable encryption (in particular `action`)? Is this because Aggregate requires using a different submission URL for encrypted records?

Related to the above, any interest in making method/action optional (either both or none), and only `base64RsaPublicKey` required to enable encryption?

**Comment by lognaturel** [comment] 2018-05-15 22:33
`action` can be used on its own for the form to specify which server it should submit to.

I think the only reason `method/action` are required with encryption is to "save people from themselves". Since encrypted forms are sent as blobs, it's particularly bad to send it to the wrong server.

That said, it's only really an issue if a form with the same `form_id` is present on two servers and basically I think users can be trusted to do the right thing. I'd be for making both method and action optional for encryption unless someone can think of another reason they may be required in the first place. 

@yanokwa, perhaps you remember something else?

**Comment by yanokwa** [comment] 2018-05-16 18:15
I do not know why `method/action` was required. It always seemed odd, but my guess is that it's by design. @wbrunette do you remember why?

It seems reasonable that all you should need is `base64RsaPublicKey` to enable encryption. And if you have `action`, then that's the URL that gets the data sent to. If you don't, then it's sent to the default on the device. If you send an encrypted blob to a server, it doesn't seem that bad because it's encyrpted.

**Comment by wbrunette** [comment] 2018-05-18 22:17
Researching this a bit I have guesses but not sure if they are accurate. 
This page was helpful:
https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Sending_and_retrieving_form_data

1) I think the "action" is there for backwards compatibility based on the statement in the article "this was required because until HTML5, the action attribute was required."
2) To make the data even more safe, based on the statement in the article "It's possible to specify a URL that uses the HTTPS (secure HTTP) protocol. When you do this, the data is encrypted along with the rest of the request, even if the form itself is hosted on an insecure page accessed using HTTP."

Again do not recall the exact reasoning these are only guesses.

Also as a clarification point (probably doesn't matter if it was just a random example url), Aggregate's submission processing servlet maps to "https://example.com/submission" not "https://example.com/submit"
https://github.com/opendatakit/aggregate/blob/master/src/main/webapp/WEB-INF/web.xml#L284

**Comment by MartijnR** [comment] 2018-05-30 16:24
Thanks @wbrunette, @yanokwa, @lognaturel.

So I think we can say that `method/action` is independent from local encryption. Ready for a PR then!

**Comment by lognaturel** [comment] 2018-05-30 19:18
Closed by #185.

**Closed as completed** 2018-06-13 17:40 UTC
