### ISSUE TITLE
Standard ODK spec differs from XML 1.0 for string

### ISSUE THREAD

**Issue by tinok** [getodk/xforms-spec#32] opened 2015-08-25 13:19 UTC
Under Data Types, we should specify that by default text entries are limited to 255 characters, and that it can be overridden in the XML (at least for Collect): 

`<bind nodeset="/nm/repeat_observation/notes" type="string" odk:length="600"/>`

https://groups.google.com/d/topic/opendatakit/2lcMAMnGoTE/discussion

**Comment by tinok** [comment] 2015-08-25 14:16
Actually not sure if the 255 character limit is still in place, current Collect no longer seems to have any limits in place.

**Comment by MartijnR** [comment] 2015-08-25 16:12
I believe this was/is purely an Aggregate thing.

On Tue, Aug 25, 2015 at 8:16 AM, Tino Kreutzer notifications@github.com
wrote:

> Actually not sure if the 255 character limit is still in place, current
> Collect no longer seems to have any limits in place.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/opendatakit/odk-xform-spec/issues/32#issuecomment-134600125
> .

## 

## 

_Revolutionizing data collection since 2012._

Enketo https://enketo.org/    |    LinkedIn 
http://www.linkedin.com/company/enketo-llc    |    GitHub 
https://github.com/enketo    |    Twitter https://twitter.com/enketo  
|    Blog http://blog.enketo.org/

**Comment by chrislrobert** [comment] 2015-08-25 16:52
Yep, and we dropped the server-side limit with SurveyCTO 1.40+. So I
believe it's only ODK Aggregate that still has that limit because of how it
stores data.

**Comment by MartijnR** [comment] 2015-08-25 17:15
Thanks.

Just saw this is a duplicate of #14.

**Closed as completed by MartijnR** 2015-08-25 17:15 UTC
